from __future__ import annotations

from abc import ABC, abstractmethod
from datetime import datetime
from typing import Any, Generic, Protocol, TypeVar

import pandas as pd
from pydantic import BaseModel

from daily_intel.core.models import Analysis, Document, Event


class SourceAdapter(Protocol):
    source_id: str

    def collect(self, since: datetime, limit: int) -> list[Document]: ...


T = TypeVar("T", bound=BaseModel)


class LLMResult(Generic[T]):
    def __init__(self, value: T, model: str, input_tokens: int = 0, output_tokens: int = 0) -> None:
        self.value = value
        self.model = model
        self.input_tokens = input_tokens
        self.output_tokens = output_tokens


class LLMClient(ABC):
    @property
    @abstractmethod
    def available(self) -> bool: ...

    @abstractmethod
    def generate(self, stage: str, system: str, user: str, schema: type[T]) -> LLMResult[T]: ...


class IntelligenceRepository(Protocol):
    def upsert_document(self, document: Document) -> bool: ...
    def update_document_content(self, document: Document) -> None: ...
    def get_documents(self, ids: list[str]) -> list[Document]: ...
    def recent_documents(self, since: datetime) -> list[Document]: ...
    def upsert_event(self, event: Event) -> None: ...
    def get_analysis(self, event_id: str) -> Analysis | None: ...
    def save_analysis(self, analysis: Analysis) -> None: ...
    def get_latest_analyses(self, limit: int) -> list[Analysis]: ...
    def record_llm_run(
        self, stage: str, event_id: str | None, model: str, prompt_version: str,
        input_tokens: int, output_tokens: int, status: str, error: str = "",
    ) -> None: ...
    def llm_usage_since(self, since: datetime) -> dict[str, int]: ...
    def get_state(self, key: str) -> str | None: ...
    def set_state(self, key: str, value: str) -> None: ...


class MarketProvider(Protocol):
    def snapshot(self, preferred: list[str]) -> Any: ...
    def industries(self) -> Any: ...
    def indices(self) -> Any: ...
    def news(self) -> Any: ...
    def trading_calendar(self) -> Any: ...
